characters = {
    "Harry Potter": {
        "shortName": "Harry",
        "other_names": ["Mr. Potter", "Harry"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Hermione Granger": {
        "shortName": "Hermione",
        "other_names": ["Hermione", "Granger"],
        "category": [
            "Female",
            "Student",
            "Child",
            "Wizard",
            "Gryffindor",
        ],
        "disqualifiers": [],
    },
    "Ron Weasley": {
        "shortName": "Ron",
        "other_names": ["Ronald", "Ron"],
        "category": ["Male", "Student", "Child", "Wizard", "Gryffindor"],
        "disqualifiers": [],
    },
    "Albus Dumbledore": {
        "shortName": "Dumbledore",
        "other_names": ["Dumbledore", "Headmaster", "Albus"],
        "category": ["Male", "Adult", "Wizard", "Headmaster", "Gryffindor"],
        "disqualifiers": [],
    },
    "Severus Snape": {
        "shortName": "Snape",
        "other_names": ["Snape", "Serverus"],
        "category": ["Male", "Adult", "Wizard", "Professor", "Slytherin"],
        "disqualifiers": [],
    },
    "Draco Malfoy": {
        "shortName": "Draco",
        "other_names": ["Draco", "Malfoy"],
        "category": ["Male", "Student", "Child", "Wizard", "Slytherin"],
        "disqualifiers": [],
    },
    "Voldemort": {
        "shortName": "Voldemort",
        "other_names": [
            "He-Who-Must-Not-Be-Named",
            "The Dark Lord",
            "Tom Riddle",
            "Tom",
            "You-Know-Who",
            "You-Know-’Oo",
        ],
        "category": ["Male", "Adult", "Wizard", "Villain", "Slytherin"],
        "disqualifiers": [],
    },
    "Hagrid": {
        "shortName": "Hagrid",
        "other_names": ["Hagrid", "Rubeus", "Gamekeeper"],
        "category": ["Male", "Adult", "Wizard", "Half-Giant", "Gryffindor"],
        "disqualifiers": [],
    },
    "Sirius Black": {
        "shortName": "Sirius",
        "other_names": ["Padfoot", "Sirius", "Black"],
        "category": ["Male", "Adult", "Wizard", "Gryffindor"],
        "disqualifiers": [],
        "books": [3, 4, 5, 6, 7],
    },
    "Remus Lupin": {
        "shortName": "Lupin",
        "other_names": ["Lupin", "Moony", "Remus"],
        "category": ["Male", "Adult", "Wizard", "Werewolf", "Gryffindor"],
        "disqualifiers": [],
        "books": [3, 4, 5, 6, 7],
    },
    "Neville Longbottom": {
        "shortName": "Neville",
        "other_names": ["Longbottom", "Neville"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Ginny Weasley": {
        "shortName": "Ginny",
        "other_names": ["Ginny"],
        "category": ["Female", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Luna Lovegood": {
        "shortName": "Luna",
        "other_names": ["Lovegood", "Luna"],
        "category": ["Female", "Child", "Wizard", "Ravenclaw", "Student"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Minerva McGonagall": {
        "shortName": "McGonagall",
        "other_names": ["McGonagall", "Minerva"],
        "category": ["Female", "Adult", "Wizard", "Gryffindor", "Professor"],
        "disqualifiers": [],
    },
    "Bellatrix Lestrange": {
        "shortName": "Bellatrix",
        "other_names": ["Bella", "Lestrange", "Lestranges"],
        "category": ["Female", "Adult", "Wizard", "Villain", "Slytherin"],
        "disqualifiers": [],
        "books": [4, 5, 6, 7],
    },
    "Molly Weasley": {
        "shortName": "Molly",
        "other_names": ["Mrs. Weasley", "Molly"],
        "category": ["Female", "Adult", "Wizard", "Gryffindor"],
        "disqualifiers": [],
    },
    "Arthur Weasley": {
        "shortName": "Arthur",
        "other_names": ["Mr. Weasley", "Arthur"],
        "category": ["Male", "Adult", "Wizard", "Gryffindor"],
        "disqualifiers": [
            "enough, Mr. Weasley",
            "Miss Granger",
            "Mr. Potter",
            "Mr. Weasley,”",
        ],
    },
    "Fred Weasley": {
        "shortName": "Fred",
        "other_names": ["Fred"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "George Weasley": {
        "shortName": "George",
        "other_names": ["George"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Dolores Umbridge": {
        "shortName": "Umbridge",
        "other_names": ["Umbridge", "Dolores"],
        "category": ["Female", "Adult", "Wizard", "Villain", "Slytherin"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Cho Chang": {
        "shortName": "Cho",
        "other_names": ["Chang", "Cho"],
        "category": ["Female", "Child", "Wizard", "Ravenclaw", "Student"],
        "disqualifiers": [],
    },
    "Cedric Diggory": {
        "shortName": "Cedric",
        "other_names": ["Diggory", "Cedric"],
        "category": ["Male", "Child", "Wizard", "Hufflepuff", "Student"],
        "disqualifiers": [],
    },
    "Lavender Brown": {
        "shortName": "Lavender",
        "other_names": ["Lavender"],
        "category": ["Female", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Parvati Patil": {
        "shortName": "Parvati",
        "other_names": ["Patil", "Parvati"],
        "category": ["Female", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Fleur Delacour": {
        "shortName": "Fleur",
        "other_names": ["Fleur", "Delacour"],
        "category": ["Female", "Adult", "Wizard", "Beauxbatons", "Triwizard Champion"],
        "disqualifiers": [],
        "books": [4, 6, 7],
    },
    "Lucius Malfoy": {
        "shortName": "Lucius",
        "other_names": ["Lucius"],
        "category": ["Male", "Adult", "Wizard", "Slytherin"],
        "disqualifiers": [],
    },
    "Narcissa Malfoy": {
        "shortName": "Narcissa",
        "other_names": ["Narcissa"],
        "category": ["Female", "Adult", "Wizard", "Slytherin"],
        "disqualifiers": [],
        "books": [6, 7],
    },
    "Pansy Parkinson": {
        "shortName": "Pansy",
        "other_names": ["Parkinson", "Pansy"],
        "category": ["Female", "Child", "Wizard", "Slytherin", "Student"],
        "disqualifiers": [],
    },
    "Gellert Grindelwald": {
        "shortName": "Grindelwald",
        "other_names": ["Grindelwald"],
        "category": ["Male", "Adult", "Wizard", "Villain"],
        "disqualifiers": [],
    },
    "Tonks": {
        "shortName": "Tonks",
        "other_names": ["Dora", "Tonks"],
        "category": ["Female", "Adult", "Wizard", "Hufflepuff", "Auror"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Moody": {
        "shortName": "Moody",
        "other_names": ["Mad-Eye Moody", "Alastor", "Moody"],
        "category": ["Male", "Adult", "Wizard", "Auror"],
        "disqualifiers": [],
        "books": [4, 5, 6, 7],
    },
    "Peter Pettigrew": {
        "shortName": "Pettigrew",
        "other_names": ["Wormtail"],
        "category": ["Male", "Adult", "Wizard", "Gryffindor", "Villain"],
        "disqualifiers": [],
        "books": [3, 4, 5, 6, 7],
    },
    "Kingsley Shacklebolt": {
        "shortName": "Kingsley",
        "other_names": ["Shacklebolt", "Kingsley"],
        "category": ["Male", "Adult", "Wizard", "Auror"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Aberforth Dumbledore": {
        "shortName": "Aberforth",
        "other_names": ["Aberforth"],
        "category": ["Male", "Adult", "Wizard", "Hog's Head Innkeeper"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Argus Filch": {
        "shortName": "Filch",
        "other_names": ["the caretaker", "Filch"],
        "category": ["Male", "Adult", "Squib", "Caretaker"],
        "disqualifiers": [],
    },
    "Gilderoy Lockhart": {
        "shortName": "Lockhart",
        "other_names": ["Lockhart", "Gilderoy"],
        "category": ["Male", "Adult", "Wizard", "Ravenclaw", "Professor"],
        "disqualifiers": [],
    },
    "Sybil Trelawney": {
        "shortName": "Trelawney",
        "other_names": ["Sybil", "Trelawney"],
        "category": ["Female", "Adult", "Wizard", "Ravenclaw", "Professor"],
        "disqualifiers": [],
        "books": [3, 4, 5, 6, 7],
    },
    "Horace Slughorn": {
        "shortName": "Slughorn",
        "other_names": ["Slughorn", "Horace"],
        "category": ["Male", "Adult", "Wizard", "Slytherin", "Professor"],
        "disqualifiers": [],
        "books": [6, 7],
    },
    "Pomona Sprout": {
        "shortName": "Sprout",
        "other_names": ["Sprout"],
        "category": ["Female", "Adult", "Wizard", "Hufflepuff", "Professor"],
        "disqualifiers": [],
    },
    "Filius Flitwick": {
        "shortName": "Flitwick",
        "other_names": ["Flitwick", "Filius"],
        "category": ["Male", "Adult", "Wizard", "Ravenclaw", "Professor"],
        "disqualifiers": [],
    },
    "Moaning Myrtle": {
        "shortName": "Myrtle",
        "other_names": ["Myrtle"],
        "category": ["Female", "Child", "Ghost", "Ravenclaw"],
        "disqualifiers": [],
        "books": [2, 3, 4, 6, 7],
    },
    "Viktor Krum": {
        "shortName": "Krum",
        "other_names": ["Viktor", "Krum"],
        "category": ["Male", "Child", "Wizard", "Durmstrang", "Triwizard Champion"],
        "disqualifiers": [],
        "books": [4, 7],
    },
    "Madam Pomfrey": {
        "shortName": "Pomfrey",
        "other_names": ["Pomfrey", "Poppy"],
        "category": ["Female", "Adult", "Wizard", "Healer"],
        "disqualifiers": [],
    },
    "Barty Crouch Jr.": {
        "shortName": "Barty Jr.",
        "other_names": ["Crouch", "Barty"],
        "category": ["Male", "Adult", "Wizard", "Villain", "Death Eater"],
        "disqualifiers": [],
        "chapters": [91, 92],
    },
    "Barty Crouch Sr.": {
        "shortName": "Crouch",
        "other_names": ["Bartemius", "Crouch", "Barty"],
        "category": ["Male", "Adult", "Wizard", "Ministry of Magic"],
        "disqualifiers": ["Crouch Jr."],
        "books": [4, 5, 6, 7],
    },
    "Rita Skeeter": {
        "shortName": "Rita",
        "other_names": ["Skeeter", "Rita"],
        "category": ["Female", "Adult", "Wizard", "Journalist"],
        "disqualifiers": [],
    },
    "Cornelius Fudge": {
        "shortName": "Fudge",
        "other_names": ["Cornelius", "Fudge"],
        "category": ["Male", "Adult", "Wizard", "Ministry of Magic"],
        "disqualifiers": [],
    },
    "Percy Weasley": {
        "shortName": "Percy",
        "other_names": ["Percy"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Ministry of Magic"],
        "disqualifiers": [],
    },
    "Dobby": {
        "shortName": "Dobby",
        "other_names": ["Dobby"],
        "category": ["Male", "Creature", "House Elf", "Adult"],
        "disqualifiers": [],
        "books": [2, 3, 4, 5, 6, 7],
    },
    "Kreacher": {
        "shortName": "Kreacher",
        "other_names": ["Kreacher"],
        "category": ["Male", "Creature", "House Elf", "Adult"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Madam Hooch": {
        "shortName": "Hooch",
        "other_names": ["Hooch"],
        "category": ["Female", "Adult", "Wizard", "Quidditch Referee"],
        "disqualifiers": [],
    },
    "Griphook": {
        "shortName": "Griphook",
        "other_names": ["Griphook"],
        "category": ["Male", "Creature", "Goblin", "Adult"],
        "disqualifiers": [],
    },
    "Firenze": {
        "shortName": "Firenze",
        "other_names": ["Firenze"],
        "category": ["Male", "Creature", "Centaur", "Professor", "Adult"],
        "disqualifiers": [],
    },
    "Oliver Wood": {
        "shortName": "Wood",
        "other_names": ["Wood", "Oliver"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Quidditch Captain"],
        "disqualifiers": [],
    },
    "Dean Thomas": {
        "shortName": "Dean",
        "other_names": ["Thomas", "Dean"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Seamus Finnigan": {
        "shortName": "Seamus",
        "other_names": ["Finnigan", "Seamus"],
        "category": ["Male", "Child", "Wizard", "Gryffindor", "Student"],
        "disqualifiers": [],
    },
    "Gregory Goyle": {
        "shortName": "Goyle",
        "other_names": ["Goyle"],
        "category": ["Male", "Child", "Wizard", "Slytherin", "Student"],
        "disqualifiers": [],
    },
    "Vincent Crabbe": {
        "shortName": "Crabbe",
        "other_names": ["Crabbe"],
        "category": ["Male", "Child", "Wizard", "Slytherin", "Student"],
        "disqualifiers": [],
    },
    "Mundungus Fletcher": {
        "shortName": "Mundungus",
        "other_names": ["Dung", "Fletcher", "Mundungus"],
        "category": ["Male", "Adult", "Wizard", "Order of the Phoenix"],
        "disqualifiers": ["dragon"],
    },
    "Fenrir Greyback": {
        "shortName": "Greyback",
        "other_names": ["Greyback", "Fenrir"],
        "category": ["Male", "Adult", "Wizard", "Villain", "Werewolf"],
        "disqualifiers": [],
        "books": [6, 7],
    },
    "Nagini": {
        "shortName": "Nagini",
        "other_names": ["Nagini"],
        "category": ["Female", "Creature", "Serpent", "Horcrux", "Adult"],
        "disqualifiers": [],
        "books": [4, 5, 6, 7],
    },
    "Winky": {
        "shortName": "Winky",
        "other_names": ["Winky"],
        "category": ["Female", "Creature", "House Elf", "Adult"],
        "disqualifiers": [],
        "books": [4, 5, 6, 7],
    },
    "Charlie Weasley": {
        "shortName": "Charlie",
        "other_names": ["Charlie"],
        "category": ["Male", "Adult", "Wizard", "Gryffindor", "Dragon Keeper"],
        "disqualifiers": [],
    },
    "Bill Weasley": {
        "shortName": "Bill",
        "other_names": ["Bill"],
        "category": ["Male", "Adult", "Wizard", "Gryffindor", "Curse Breaker"],
        "disqualifiers": [],
    },
    "Aunt Petunia": {
        "shortName": "Petunia",
        "other_names": ["Petunia", "Mrs. Dursley"],
        "category": ["Female", "Adult", "Muggle", "Dursley Family"],
        "disqualifiers": [],
    },
    "Vernon Dursley": {
        "shortName": "Vernon",
        "other_names": ["Vernon", "Mr. Dursley"],
        "category": ["Male", "Adult", "Muggle", "Dursley Family"],
        "disqualifiers": [],
    },
    "Dudley Dursley": {
        "shortName": "Dudley",
        "other_names": ["Dudders", "Dudley"],
        "category": ["Male", "Child", "Muggle", "Dursley Family"],
        "disqualifiers": [],
    },
    "Grawp": {
        "shortName": "Grawp",
        "other_names": ["Grawp"],
        "category": ["Male", "Creature", "Giant", "Adult"],
        "disqualifiers": [],
        "books": [5, 6, 7],
    },
    "Rufus Scrimgeour": {
        "shortName": "Scrimgeour",
        "other_names": ["Scrimgeour", "Rufus"],
        "category": ["Male", "Adult", "Wizard", "Ministry of Magic"],
        "disqualifiers": [],
        "books": [6, 7],
    },
    "Augusta Longbottom": {
        "shortName": "Augusta",
        "other_names": ["Gran", "Augusta"],
        "category": ["Female", "Adult", "Wizard", "Longbottom Family"],
        "disqualifiers": [],
    },
    "Madam Rosmerta": {
        "shortName": "Rosmerta",
        "other_names": ["Rosmerta"],
        "category": ["Female", "Adult", "Wizard", "Three Broomsticks"],
        "disqualifiers": [],
    },
    "Aragog": {
        "shortName": "Aragog",
        "other_names": ["Acromantula"],
        "category": ["Male", "Creature", "Acromantula", "Adult"],
        "disqualifiers": [],
    },
    "Fang": {
        "shortName": "Fang",
        "other_names": ["Hagrid's Dog"],
        "category": ["Male", "Creature", "Dog", "Adult"],
        "disqualifiers": [],
    },
    "Buckbeak": {
        "shortName": "Buckbeak",
        "other_names": ["Witherwings"],
        "category": ["Male", "Creature", "Hippogriff", "Adult"],
        "disqualifiers": [],
        "books": [3, 4, 5, 6, 7],
    },
    "Errol": {
        "shortName": "Errol",
        "other_names": [],
        "category": ["Male", "Creature", "Owl", "Adult"],
        "disqualifiers": [],
    },
    "Pigwidgeon": {
        "shortName": "Pigwidgeon",
        "other_names": ["Pig"],
        "category": ["Male", "Creature", "Owl", "Adult"],
        "disqualifiers": [],
        "books": [4, 5, 6, 7],
    },
    "Hedwig": {
        "shortName": "Hedwig",
        "other_names": ["Harry's Owl"],
        "category": ["Female", "Creature", "Owl", "Adult"],
        "disqualifiers": [],
    },
}
