double_names = [
    "Serafina Pekkala",
    "Lee Scoresby",
    "Jake Petersen",
    "Simon Parslow",  # disqualifiers "Hartmann"
    "Semyon Borisovitch",
    "Jacob Huismans",
    "Iofur Raknison",
    "Mary Malone",
    "Chevalier Tialys",
    "Ruta Skadi",
    "Nicholas Rokeby",
    "Lena Feldt",
    "Oliver Payne",
    "Giacomo Paradisi",
    "Tony Makarios",
    "Sayan Kötör",
    "Adèle Starminster",
    "Joachim Lorenz",
    # "Dirk Jansen",
    # "Sam Cansino",
    "Bernie Johansen",
    "Fra Pavel",
    "Otyets Semyon",
    # "Hugh Lovat",
    "Jessie Reynolds",
]

single_names = [
    # "Abbey",
    # "Abingdon",
    # "Academicians",
    # "Academy",
    # "Act",
    # "Ad",
    # "Adam",
    # "Afric",
    # "Africa",
    # "African",
    # "Africans",
    "Agnes",
    # "Alamo",
    "Alan",
    # "Alaska",
    # "Alexandrovna",
    "Alfredo",
    "Allan",
    # "Almighty",
    # "Alpine",
    # "Alps",
    "Ama",
    # "Ambassador",
    # "American",
    # "Americans",
    # "Amsterdam",
    # "Anbaric",
    # "Ancient",
    # "And",
    "Andersson",
    "Anfang",
    # "Angeli",
    "Angelica",
    # "Angels",
    "Annie",
    # "Apocalypse",
    # "Arabic",
    # "Archaeology",
    # "Arctic",
    # "Arrow",
    # "As",
    "Ashmolean",
    # "Asia",
    # "Asian",
    # "Asiatic",
    "Asphaltus",
    # "Asriel",
    # "Assyrians",
    # "At",
    "Atal",
    # "Atlantic",
    # "August",
    # "Aurora",
    # "Australia",
    # "Authority",
    "Autumnal",
    "Balliol",
    "Balthamos",
    # "Baltic",
    # "Banbury",
    # "Bank",
    # "Bar",
    # "Barnard",
    # "Baruch",
    # "Basilides",
    # "Battlements",
    # "Beats",
    # "Before",
    # "Belacqua",
    "Belisaria",
    # "Bella",
    # "Benin",
    "Benjamin",
    "Bergamo",
    # "Bering",
    "Beringland",
    # "Berlin",
    # "Bernie",
    # "Bible",
    # "Big",
    # "Bigfoot",
    "Billy",
    # "Bird",
    # "Bishops",
    # "Black",
    # "Bliss",
    # "Board",
    # "Bodley",
    # "Bolvangar",
    # "Book",
    # "Boreal",
    # "Boris",
    # "Borisovitch",
    # "Botanic",
    # "Bourne",
    # "Boy",
    "Braks",
    # "Brasil",
    # "Breathless",
    "Bridget",
    # "Brings",
    # "Bristol",
    # "Broad",
    # "Bronze",
    # "Broogs",
    # "Brooks",
    # "Brother",
    # "Burger",
    # "Burgundy",
    # "But",
    # "Butler",
    # "Byrnison",
    # "Cabinet",
    # "Cake",
    # "California",
    # "Calvin",
    # "Canal",
    # "Canary",
    # "Cansino",
    "Canzona",
    # "Captain",
    # "Cardinal",
    # "Caribbean",
    # "Cassington",
    # "Castor",
    # "Catching",
    "Cathay",
    # "Catholic",
    # "Catte",
    # "Cave",
    # "Central",
    # "Ch",
    # "Changes",
    # "Chapel",
    # "Chaplain",
    # "Chapter",
    # "Chariot",
    # "Charles",
    "Charlie",
    # "Chef",
    "Cherwell",
    # "Chevalier",
    # "China",
    # "Chinese",
    # "Ching",
    # "Cho",
    # "Christian",
    # "Chthonic",
    # "Church",
    # "Chymist",
    # "Ci",
    "Citt",
    "Clara",
    # "Claybeds",
    "Clerkenwell",
    # "Climbing",
    # "Cloud",
    # "Clouded",
    # "Coca",
    # "Coke",
    # "Colby",
    "Cole",
    # "College",
    # "Colonel",
    # "Colville",
    # "Company",
    # "Concilium",
    # "Consistorial",
    # "Consul",
    # "Coram",
    "Corea",
    # "Cornmarket",
    # "Cosmology",
    # "Costa",
    # "Costas",
    # "Coulter",
    # "Council",
    # "Court",
    # "Cousins",
    # "Covered",
    "Cowley",
    # "Creator",
    # "Cressets",
    # "Dada",
    # "Dame",
    # "Dance",
    "Danes",
    "Daniel",
    # "Dark",
    # "Darling",
    "Davy",
    # "Days",
    # "Dean",
    # "Death",
    # "Defense",
    # "Denmark",
    # "Department",
    # "Devil",
    "Dick",
    # "Director",
    # "Dirk",
    # "Discipline",
    # "Dr",
    # "Duchess",
    # "Duke",
    # "Dunno",
    # "Dust",
    # "Dutch",
    # "Each",
    # "East",
    # "Eastern",
    # "Ecclesiast",
    # "Eden",
    "Edward",
    # "Egypt",
    # "Einarsson",
    "Eireland",
    "Eisarson",
    "Elaine",
    # "Embankment",
    # "Eminence",
    # "Emperor",
    # "Empire",
    # "England",
    # "English",
    # "Englishman",
    "Enoch",
    "Enosh",
    "Enquirer",
    "Erik",
    # "Eskimo",
    # "Europe",
    # "European",
    "Eve",
    # "Evil",
    # "Experimental",
    # "Exploration",
    # "Faa",
    "Fairbanks",
    # "Fairyland",
    # "Falkeshall",
    # "Fall",
    # "Farder",
    "Farr",
    # "Father",
    # "Feldt",
    # "Fen",
    # "Fens",
    # "Fights",
    # "Fine",
    # "For",
    # "Fra",
    "Frans",
    # "French",
    # "From",
    # "Frowning",
    # "Fruit",
    # "Gabriel",
    # "Gallivespian",
    # "Gallivespians",
    # "Garden",
    # "General",
    # "Genesis",
    # "Geneva",
    # "Genius",
    "Gerard",
    # "German",
    # "Gerrit",
    # "Giacomo",
    # "Gloucester",
    # "Gobbler",
    # "Gobblers",
    # "God",
    "Godstow",
    "Gomez",
    # "Gracious",
    # "Grand",
    # "Grandpa",
    # "Great",
    # "Greek",
    # "Greenland",
    "Grimssdur",
    # "Grumman",
    # "Guard",
    # "Guild",
    # "Hall",
    # "Hampshire",
    # "Hang",
    # "Hangman",
    "Hannah",
    "Hartmann",
    # "Headington",
    "Heav",
    # "Heaven",
    "Heidelberg",
    # "Hell",
    "Henley",
    # "Here",
    "Hester",
    "Heyst",
    # "High",
    # "Him",
    # "Himalaya",
    # "Himalayan",
    "Hindus",
    # "His",
    "Hjalmur",
    "Hjalmurson",
    # "Holland",
    "Hollanders",
    # "Hollands",
    # "Holy",
    # "House",
    # "Housekeeper",
    "Hugh",
    # "Humanity",
    # "Iceland",
    "Ieva",
    # "Imperial",
    "Indies",
    # "Indifference",
    # "Inquirer",
    # "Inquisition",
    # "Inspector",
    # "Institute",
    # "Intercessor",
    # "Inuit",
    # "Iofur",
    # "Iorek",
    # "Irish",
    "Isis",
    # "It",
    # "Italian",
    # "Ivan",
    # "Ivanovitch",
    "Izmir",
    # "Jack",
    # "Jacob",
    # "Jake",
    # "Jansen",
    "Jared",
    # "Jericho",
    "Jerry",
    # "Jessie",
    # "Jesus",
    # "Joachim",
    # "Johansen",
    # "John",
    # "Johnny",
    # "Jopari",
    # "Jordan",
    # "June",
    "Juta",
    "Kaisa",
    "Kamainen",
    "Kamchatka",
    "Karossa",
    # "Keats",
    "Kenan",
    # "Kendal",
    "Kerim",
    "Kholodnoye",
    "Kigalik",
    # "King",
    # "Kingdom",
    "Kirjava",
    "Kulang",
    "Kyrillion",
    # "Labour",
    # "Lady",
    # "Lake",
    # "Land",
    "Langlokur",
    # "Lapland",
    "Lascar",
    # "Latrom",
    # "Latvia",
    # "Latvian",
    # "Lee",
    # "Lena",
    # "Let",
    # "Librarian",
    # "Library",
    # "Like",
    "Limehouse",
    # "Lion",
    "Lisa",
    # "Lisbon",
    # "Lizzie",
    # "Lodge",
    # "London",
    # "Lookout",
    # "Lord",
    # "Lordship",
    # "Lorenz",
    "Louis",
    # "Lovat",
    "Luis",
    "Lydia",
    # "Lyra",
    "Lyratic",
    # "Ma",
    "Mac",
    # "Madame",
    # "Madonna",
    "Magda",
    "Magdalen",
    # "Magic",
    # "Magisterium",
    "Magnusson",
    "Mahalalel",
    # "Maidenhead",
    # "Majesty",
    # "Major",
    # "Makarios",
    "Makepwe",
    # "Malone",
    # "Mama",
    # "Manchester",
    # "March",
    # "Marines",
    # "Marisa",
    # "Mark",
    # "Mars",
    # "Martha",
    "Martin",
    # "Mary",
    # "Mass",
    # "Master",
    # "Masters",
    "Matapan",
    # "Maystadt",
    # "Mc",
    # "Mediterranean",
    # "Melrose",
    "Metatron",
    # "Middle",
    # "Midlands",
    # "Midsummer",
    # "Milky",
    # "Ministry",
    # "Mississippi",
    # "Monday",
    "Monica",
    # "Moon",
    # "Morocco",
    "Mortlake",
    "Moses",
    # "Mother",
    # "Mountain",
    "Moxie",
    # "Mr",
    # "Mrs",
    # "Mum",
    # "Mummy",
    # "Muscovite",
    # "Muscovites",
    # "Muscovy",
    # "Museum",
    # "My",
    "Naphtha",
    # "Nature",
    # "Navajo",
    "Nellie",
    "Nelson",
    # "New",
    # "Next",
    # "Nicholas",
    "Nippon",
    # "Nipponese",
    # "No",
    "Noatak",
    # "Noon",
    "Norham",
    # "Norroway",
    # "North",
    # "Northampton",
    # "Northern",
    # "Northlanders",
    # "Norwegian",
    "Norwich",
    # "Nottingham",
    # "Nova",
    # "Now",
    "Nuniatak",
    # "Ob",
    # "Obedience",
    # "Oblation",
    # "Observatory",
    # "Ocean",
    # "Of",
    # "Office",
    # "Official",
    "Ogunwe",
    # "Oliver",
    # "On",
    # "Once",
    "Opal",
    "Ophiuchus",
    # "Oratory",
    # "Otyets",
    "Oxentiel",
    # "Oxford",
    # "Oxfordshire",
    "Pagdzin",
    # "Palace",
    "Palmer",
    # "Palmerian",
    # "Pan",
    # "Panama",
    # "Pantalaimon",
    "Paolo",
    # "Papacy",
    # "Paradisi",
    # "Parliament",
    # "Parry",
    # "Parslow",
    # "Parslows",
    # "Pavel",
    # "Payne",
    # "Peaceable",
    # "Pekkala",
    "Pete",
    # "Peter",
    # "Ph",
    # "Pharaohs",
    # "Physical",
    # "Pie",
    # "Pilgrim",
    "Pitt",
    # "Plato",
    # "Polar",
    # "Pole",
    # "Pope",
    "Popes",
    "Poppel",
    # "Port",
    # "Porter",
    # "Portugal",
    "Pounding",
    # "Prague",
    "Precentor",
    # "President",
    # "Prime",
    # "Princess",
    # "Professor",
    # "Prophecy",
    # "Publications",
    # "Queen",
    "Rainer",
    # "Raknison",
    "Rasek",
    "Ratter",
    "Raymond",
    # "Regent",
    "Regius",
    "Reina",
    "Relf",
    # "Republic",
    # "Research",
    # "Retiring",
    # "Reviving",
    "Reynolds",
    # "Rilke",
    # "River",
    "Roarer",
    # "Roger",
    # "Roke",
    # "Rokeby",
    # "Rolls",
    # "Roman",
    # "Room",
    # "Roping",
    # "Royal",
    # "Rusakov",
    # "Russian",
    # "Russians",
    # "Ruta",
    "Ruud",
    # "Ruyter",
    # "Saint",
    "Sakhalin",
    # "Salcilia",
    # "Salmakia",
    # "Sam",
    # "Samirsky",
    # "Samoyed",
    # "Samoyeds",
    # "Sandling",
    # "Sant",
    "Santelia",
    # "Saphire",
    "Satanic",
    "Sattamax",
    # "Saturday",
    # "Sayan",
    # "Scholar",
    # "Scholars",
    # "Scoresby",
    # "Scot",
    # "Scotland",
    # "Secretariat",
    # "Semyon",
    # "Semyonov",
    # "Senior",
    # "Serafina",
    # "Sergeant",
    "Seth",
    # "Shadow",
    # "Shadows",
    # "She",
    "Sheffield",
    # "Sheldon",
    "Shew",
    # "Ship",
    # "Shot",
    # "Siberia",
    # "Siberian",
    "Sibirsk",
    # "Silver",
    # "Silvertongue",
    # "Simon",
    # "Sin",
    # "Sir",
    # "Sister",
    # "Sisters",
    # "Skadi",
    # "Skraeling",
    # "Skraelings",
    # "Smokemarket",
    # "Society",
    # "Somebody",
    "Sophonax",
    # "South",
    # "Soviet",
    # "Soviets",
    # "Spanish",
    # "Special",
    # "Specter",
    # "Spectereaten",
    # "Specters",
    # "Spectre",
    # "Sphinx",
    # "Squadron",
    # "St",
    # "Staircase",
    "Stan",
    # "Stanislaus",
    # "Starminster",
    "Starry",
    # "State",
    # "Station",
    # "Stefanski",
    "Stelmaria",
    "Stephen",
    # "Steps",
    # "Steward",
    # "Still",
    # "Stokes",
    "Stratford",
    # "Sturrock",
    # "Sub",
    # "Sultan",
    # "Summertown",
    # "Sun",
    # "Sunderland",
    # "Sungchen",
    # "Survey",
    # "Svalbard",
    # "Sveden",
    # "Sweet",
    # "Swiss",
    # "Tartar",
    # "Tartars",
    "Teddington",
    # "Teflon",
    # "Temptation",
    "Teukros",
    # "Texan",
    # "Texas",
    "Thames",
    # "The",
    # "Then",
    # "Theology",
    # "There",
    # "Thick",
    "Thir",
    # "Third",
    # "This",
    "Thorold",
    # "Tialys",
    # "Tibet",
    # "Tokay",
    "Tom",
    # "Tony",
    # "Torre",
    # "Tower",
    # "Transit",
    # "Trees",
    "Trelawney",
    # "Trollesund",
    "Tullio",
    "Tungusk",
    # "Tunguska",
    # "Turk",
    # "Turkestan",
    # "Turkish",
    # "Turks",
    "Turl",
    "Twigs",
    # "Umaq",
    # "Uncle",
    # "University",
    "Uppsala",
    "Urals",
    "Vallombrosa",
    # "Van",
    # "Vatican",
    # "Venus",
    # "Vice",
    # "Victorian",
    "Virginia",
    "Volgorsk",
    "Vries",
    # "Walk",
    "Walters",
    # "Wapping",
    # "Wars",
    # "Watchers",
    # "Watercourse",
    "Watlington",
    # "Wednesday",
    "Wells",
    # "Westminster",
    # "Wharf",
    # "White",
    # "Will",
    # "William",
    # "Winchester",
    # "Winds",
    # "Windsuckers",
    # "Wings",
    # "Wisdom",
    # "Witches",
    # "Wolf",
    # "Work",
    "Xaphania",
    "Yakovlev",
    # "Yambe",
    "Yarnton",
    "Yaxley",
    # "Yenisei",
    "Yoruba",
    # "Zaal",
    "Zaire",
    "Zoroastrian",
]
