characters_list = [
    {"name": "Lyra", "other_names": ["Lizzie", "Silvertounge"], "category": "Child"},
    {
        "name": "Lord Asriel",
        "other_names": ["Asriel"],
    },
    {"name": "Roger", "category": "Child"},
    {"name": "Yambe-Akka", "category": "Witch"},
    {
        "name": "Will",
        "other_names": ["William", "Mark"],
        "disqualifiers": ["Will you", "Will I", "Will he", "Will she"],
    },
    {"name": "Pantalaimon", "other_names": ["Pan"], "category": "Dæmon"},
    {
        "name": "Mrs. Coulter",
        "count": 0,
        "char_count": [],
        "disqualifiers": ["Mr. Coulter"],
        "other_names": ["Marisa", "Coulter"],
    },
    {"name": "Lord Faa", "other_names": ["John Faa"], "category": "Gyptian"},
    {"name": "Farder Coram", "category": "Gyptian"},
    {"name": "Ma Costa", "other_names": ["Mrs. Costa"], "category": "Gyptian"},
    {"name": "Billy", "category": "Gyptian", "category": "Child"},
    {
        "name": "Father MacPhail",
        "count": 0,
        "char_count": [],
        "other_names": ["MacPhail"],
        "disqualifiers": ["Hugh MacPhail"],
        "category": "Cleric",
    },
    {
        "name": "Sir Charles",
        "count": 0,
        "char_count": [],
        "other_names": ["Latrom", "Boreal"],
    },
    {
        "name": "lorek Byrnison",
        "count": 0,
        "char_count": [],
        "other_names": ["lorek", "Byrnison", "Iorek"],
        "category": "Bear",
    },
    {
        "name": "John Parry",
        "count": 0,
        "char_count": [],
        "other_names": ["Parry", "Stanislaus", "Grumman", "Johnny", "John", "Jopari"],
        "disqualifiers": [
            "Mrs. Parry",
            "Will Parry",
            "William Parry",
            "Johnny Fiorelli",
            "John Faa",
            "growed up, John",
        ],
    },
    {
        "name": "The Master",
        "other_names": ["Master", "Charles"],
        "disqualifiers": ["Sir Charles", "Latrom", "Master Will", "I’m Charles."],
    },
    {
        "name": "golden monkey",
        "other_names": ["monkey"],
        "disqualifiers": ["monkey faces", "monkey in the trees"],
        "category": "Dæmon",
    },
    {"name": "Lady Salmakia", "other_names": ["Salmakia"], "category": "Gallivespian"},
    {"name": "Lord Roke", "other_names": ["Roke"], "category": "Gallivespian"},
    {
        "name": "Serafina Pekkala",
        "other_names": ["Serafina", "Pekkala"],
        "category": "Witch",
    },
    {"name": "Lee Scoresby", "other_names": ["Lee", "Scoresby"]},
    {"name": "Jake Petersen", "other_names": ["Jake", "Petersen"]},
    {
        "name": "Simon Parslow",
        "other_names": ["Simon", "Parslow"],
        "disqualifiers": ["Hartmann", "Roger"],
    },
    {"name": "Semyon Borisovitch", "other_names": ["Semyon", "Borisovitch"]},
    {"name": "Jacob Huismans", "other_names": ["Jacob", "Huismans"]},
    {
        "name": "Iofur Raknison",
        "other_names": ["Iofur", "Raknison"],
        "category": "Bear",
    },
    {"name": "Mary Malone", "other_names": ["Mary", "Malone"]},
    {
        "name": "Chevalier Tialys",
        "other_names": ["Chevalier", "Tialys"],
        "category": "Gallivespian",
    },
    {"name": "Ruta Skadi", "other_names": ["Ruta", "Skadi"], "category": "Witch"},
    {"name": "Nicholas Rokeby", "other_names": ["Nicholas", "Rokeby"]},
    {"name": "Lena Feldt", "other_names": ["Lena", "Feldt"], "category": "Witch"},
    {"name": "Oliver Payne", "other_names": ["Oliver", "Payne"]},
    {"name": "Giacomo Paradisi", "other_names": ["Giacomo", "Paradisi"]},
    {"name": "Tony Makarios", "other_names": ["Tony", "Makarios"], "category": "Child"},
    {"name": "Sayan Kötör", "other_names": ["Sayan", "Kötör"]},
    {"name": "Adèle Starminster", "other_names": ["Adèle", "Starminster"]},
    {"name": "Joachim Lorenz", "other_names": ["Joachim", "Lorenz"]},
    {"name": "Bernie Johansen", "other_names": ["Bernie", "Johansen"]},
    {"name": "Fra Pavel", "other_names": ["Fra", "Pavel"], "category": "Cleric"},
    {"name": "Jessie Reynolds", "other_names": ["Jessie", "Reynolds"]},
    {"name": "Hester", "category": "Dæmon"},
    {"name": "Balthamos", "category": "Angel"},
    {"name": "Baruch", "category": "Angel"},
    {"name": "Ama", "category": "Child"},
    {"name": "Atal", "category": "Mulefa"},
    {"name": "King Ogunwe", "other_names": ["Ogunwe"]},
    {"name": "Father Gomez", "other_names": ["Gomez"], "category": "Cleric"},
    {"name": "Angelica", "category": "Child"},
    {"name": "Thorold"},
    {"name": "Kirjava", "category": "Dæmon"},
    {"name": "Paolo", "category": "Child"},
    {"name": "Xaphania", "category": "Angel"},
    {"name": "Metatron", "category": "Angel"},
    {"name": "Dame Hannah", "other_names": ["Hannah"]},
    {"name": "Brother Louis", "other_names": ["Louis"], "category": "Cleric"},
    {"name": "Annie", "category": "Child"},
    {"name": "Tullio"},
    {"name": "Sister Clara", "other_names": ["Clara"]},
    {"name": "Ratter", "category": "Dæmon"},
    {"name": "Trelawney"},
    {"name": "Sattamax", "category": "Dæmon"},
    {"name": "Kaisa", "category": "Dæmon"},
]
