characters = {
    # Sense and Sensibility
    "Elinor Dashwood": {
        "name": "Elinor Dashwood",
        "other_names": ["Elinor", "Miss Dashwood", "Miss Dashwoods"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": ["Mrs. Dashwood", "Mr. Dashwood"],
        "books": [1],
    },
    "Marianne Dashwood": {
        "name": "Marianne Dashwood",
        "other_names": ["Marianne", "Miss Dashwoods"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Colonel Brandon": {
        "name": "Colonel Brandon",
        "other_names": ["Colonel", "Brandon"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [1],
    },
    "Edward Ferrars": {
        "name": "Edward Ferrars",
        "other_names": ["Edward", "Mr. Ferrars"],
        "category": ["Male", "Unmarried", "Clergy"],
        "disqualifiers": [],
        "books": [1],
    },
    "Mrs. Dashwood": {
        "name": "Mrs. Dashwood",
        "other_names": ["Dashwood"],
        "category": ["Female", "Widowed", "No profession"],
        "disqualifiers": ["Mr. Dashwood", "John Dashwood"],
        "books": [1],
    },
    "John Dashwood": {
        "name": "John Dashwood",
        "other_names": [],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Fanny Dashwood": {
        "name": "Fanny Dashwood",
        "other_names": ["Fanny"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Margaret Dashwood": {
        "name": "Margaret Dashwood",
        "other_names": ["Margaret"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Sir John Middleton": {
        "name": "Sir John Middleton",
        "other_names": ["Middleton"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Mrs. Jennings": {
        "name": "Mrs. Jennings",
        "other_names": [],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Lucy Steele": {
        "name": "Lucy Steele",
        "other_names": ["Lucy", "Steele"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": ["Anne"],
        "books": [1],
    },
    "Anne Steele": {
        "name": "Anne Steele",
        "other_names": ["Anne"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Robert Ferrars": {
        "name": "Robert Ferrars",
        "other_names": ["Robert"],
        "category": ["Male", "Unmarried", "Politics"],
        "disqualifiers": [],
        "books": [1],
    },
    "Mrs. Ferrars": {
        "name": "Mrs. Ferrars",
        "other_names": [],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    "Mr. Willoughby": {
        "name": "Willoughby",
        "other_names": [],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [1],
    },
    # Pride and Prejudice
    "Lizzie Bennet": {
        "name": "Lizzie Bennet",
        "other_names": ["Elizabeth", "Eliza", "Lizzie", "Miss Bennet"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Jane Bennet": {
        "name": "Jane Bennet",
        "other_names": ["Miss Bennet", "Jane"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Darcy": {
        "name": "Mr. Darcy",
        "other_names": ["Darcy"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Bingley": {
        "name": "Mr. Bingley",
        "other_names": ["Charles Bingley", "Bingley", "Charles"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": ["Miss Bingley"],
        "books": [2],
    },
    "Caroline Bingley": {
        "name": "Caroline Bingley",
        "other_names": ["Caroline", "Miss Bingley"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Bennet": {
        "name": "Mr. Bennet",
        "other_names": ["Mr Bennet", "Mr.Bennet"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mrs. Bennet": {
        "name": "Mrs. Bennet",
        "other_names": [],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Collins": {
        "name": "Mr. Collins",
        "other_names": ["William Collins", "Collins"],
        "category": ["Male", "Unmarried", "Clergy"],
        "disqualifiers": [],
        "books": [2],
    },
    "Charlotte Lucas": {
        "name": "Charlotte Lucas",
        "other_names": ["Miss Lucas", "Charlotte"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Lady Catherine": {
        "name": "Lady Catherine",
        "other_names": ["Lady Catherine de Bourgh", "de Bourgh"],
        "category": ["Female", "Widowed", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Wickham": {
        "name": "Mr. Wickham",
        "other_names": ["George Wickham", "Wickham", "George"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [2],
    },
    "Lydia Bennet": {
        "name": "Lydia Bennet",
        "other_names": ["Lydia"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mary Bennet": {
        "name": "Mary Bennet",
        "other_names": ["Mary"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Kitty Bennet": {
        "name": "Kitty Bennet",
        "other_names": ["Kitty"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [2],
    },
    "Mr. Gardiner": {
        "name": "Mr. Gardiner",
        "other_names": ["Gardiner"],
        "category": ["Male", "Married", "Law"],
        "disqualifiers": ["Mrs. Gardiner"],
        "books": [2],
    },
    "Mrs. Gardiner": {
        "name": "Mrs. Gardiner",
        "other_names": ["Gardiner"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": ["Mr. Gardiner"],
        "books": [2],
    },
    "Colonel Fitzwilliam": {
        "name": "Colonel Fitzwilliam",
        "other_names": ["Colonel", "Fitzwilliam"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": ["Darcy"],
        "books": [2],
    },
    ## Northanger Abbey
    "Catherine Morland": {
        "name": "Catherine Morland",
        "other_names": ["Catherine", "Miss Morland"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "Henry Tilney": {
        "name": "Henry Tilney",
        "other_names": ["Henry"],
        "category": ["Male", "Unmarried", "Clergy"],
        "disqualifiers": [],
        "books": [3],
    },
    "Eleanor Tilney": {
        "name": "Eleanor Tilney",
        "other_names": ["Eleanor", "Miss Tilney"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "General Tilney": {
        "name": "General Tilney",
        "other_names": ["General"],
        "category": ["Male", "Widowed", "Military"],
        "disqualifiers": [],
        "books": [3],
    },
    "Isabella Thorpe": {
        "name": "Isabella Thorpe",
        "other_names": ["Isabella", "Miss Thorpe"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "James Morland": {
        "name": "James Morland",
        "other_names": ["James"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "John Thorpe": {
        "name": "John Thorpe",
        "other_names": ["John", "Mr. Thorpe"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "Mrs. Morland": {
        "name": "Mrs. Morland",
        "other_names": ["Mrs. Morland", "Mrs Morland"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "Mrs. Allen": {
        "name": "Mrs. Allen",
        "other_names": ["Mrs. Allen", "Mrs Allen"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    "Captain Frederick Tilney": {
        "name": "Captain Frederick Tilney",
        "other_names": ["Frederick", "Captain Tilney", "Captain"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [3],
    },
    "Mr. Allen": {
        "name": "Mr. Allen",
        "other_names": ["Mr. Allen"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [3],
    },
    ## Mansfield Park
    "Fanny Price": {
        "name": "Fanny Price",
        "other_names": ["Fanny", "Miss Price"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Edmund Bertram": {
        "name": "Edmund Bertram",
        "other_names": ["Edmund Bertram", "Edmund"],
        "category": ["Male", "Unmarried", "Clergy"],
        "disqualifiers": [],
        "books": [4],
    },
    "Sir Thomas Bertram": {
        "name": "Sir Thomas Bertram",
        "other_names": ["Sir Thomas Bertram", "Thomas"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Lady Bertram": {
        "name": "Lady Bertram",
        "other_names": ["Lady Bertram"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Maria Bertram": {
        "name": "Maria Bertram",
        "other_names": ["Maria"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Julia Bertram": {
        "name": "Julia Bertram",
        "other_names": ["Julia"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Tom Bertram": {
        "name": "Tom Bertram",
        "other_names": ["Tom"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Mrs. Norris": {
        "name": "Mrs. Norris",
        "other_names": ["Mrs. Norris", "Mrs Norris", "Norris"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": ["Mr. Norris"],
        "books": [4],
    },
    "Henry Crawford": {
        "name": "Henry Crawford",
        "other_names": ["Henry Crawford", "Henry", "Mr. Crawford"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Mary Crawford": {
        "name": "Mary Crawford",
        "other_names": ["Mary Crawford", "Mary", "Miss Crawford"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    "Mr. Rushworth": {
        "name": "Mr. Rushworth",
        "other_names": ["Mr. Rushworth", "Rushworth"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": ["Mrs. Rushworth"],
        "books": [4],
    },
    "Mrs. Rushworth": {
        "name": "Mrs. Rushworth",
        "other_names": [],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": ["Mr. Rushworth"],
        "books": [4],
    },
    "William Price": {
        "name": "William Price",
        "other_names": ["William"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [4],
    },
    "Mrs. Price": {
        "name": "Mrs. Price",
        "other_names": ["Mrs. Price", "Mrs Price"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [4],
    },
    ## Emma
    "Emma Woodhouse": {
        "name": "Emma Woodhouse",
        "other_names": ["Emma", "Miss Woodhouse"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mr. Knightley": {
        "name": "Mr. Knightley",
        "other_names": ["Mr. Knightley", "Knightley"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": ["Mrs. Knightley", "Isabella Knightley"],
        "books": [5],
    },
    "Harriet Smith": {
        "name": "Harriet Smith",
        "other_names": ["Harriet", "Smith"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mr. Weston": {
        "name": "Mr. Weston",
        "other_names": ["Mr. Weston"],
        "category": ["Male", "Married", "Military"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mrs. Weston": {
        "name": "Mrs. Weston",
        "other_names": ["Mrs. Weston", "Mrs Weston", "Taylor", "Anne"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Frank Churchill": {
        "name": "Frank Churchill",
        "other_names": ["Frank", "Churchill"],
        "category": ["Male", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Jane Fairfax": {
        "name": "Jane Fairfax",
        "other_names": ["Jane Fairfax", "Jane", "Fairfax"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mr. Elton": {
        "name": "Mr. Elton",
        "other_names": ["Elton", "Eltons"],
        "category": ["Male", "Unmarried", "Clergy"],
        "disqualifiers": ["Augusta Elton", "Mrs. Elton", "Miss Elton"],
        "books": [5],
    },
    "Augusta Hawkins": {
        "name": "Augusta Hawkins",
        "other_names": ["Augusta", "Miss Hawkins", "Mrs. Elton", "Eltons"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Miss Bates": {
        "name": "Miss Bates",
        "other_names": ["Miss Bates"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mr. Woodhouse": {
        "name": "Mr. Woodhouse",
        "other_names": ["Mr. Woodhouse"],
        "category": ["Male", "Widowed"],
        "disqualifiers": [],
        "books": [5],
    },
    "Isabella Knightley": {
        "name": "Isabella Knightley",
        "other_names": ["Isabella"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    "Mrs. Bates": {
        "name": "Mrs. Bates",
        "other_names": ["Mrs. Bates", "Mrs Bates"],
        "category": ["Female", "Widowed", "No profession"],
        "disqualifiers": [],
        "books": [5],
    },
    ## Persuasion
    "Anne Elliot": {
        "name": "Anne Elliot",
        "other_names": ["Anne"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Captain Frederick Wentworth": {
        "name": "Captain Frederick Wentworth",
        "other_names": ["Wentworth", "Frederick"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [6],
    },
    "Sir Walter Elliot": {
        "name": "Sir Walter Elliot",
        "other_names": ["Sir Walter Elliot", "Walter", "Sir Elliot"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": ["William Walter Elliot"],
        "books": [6],
    },
    "Elizabeth Elliot": {
        "name": "Elizabeth Elliot",
        "other_names": ["Elizabeth", "Miss Elliot"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Mr. Elliot": {
        "name": "Mr. Elliot",
        "other_names": ["William"],
        "category": ["Male", "Unmarried"],
        "disqualifiers": [],
        "books": [6],
    },
    "Lady Russell": {
        "name": "Lady Russell",
        "other_names": ["Lady Russell", "Russell"],
        "category": ["Female", "Widowed", "No profession"],
        "disqualifiers": ["Mr. Russell"],
        "books": [6],
    },
    "Mary Musgrove": {
        "name": "Mary Musgrove",
        "other_names": ["Mary", "Mrs. Musgrove"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Charles Musgrove": {
        "name": "Charles Musgrove",
        "other_names": ["Charles"],
        "category": ["Male", "Married", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Henrietta Musgrove": {
        "name": "Henrietta Musgrove",
        "other_names": ["Henrietta", "Miss Musgrove"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Louisa Musgrove": {
        "name": "Louisa Musgrove",
        "other_names": ["Louisa"],
        "category": ["Female", "Unmarried", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Captain Benwick": {
        "name": "Captain Benwick",
        "other_names": ["Benwick"],
        "category": ["Male", "Unmarried", "Military"],
        "disqualifiers": [],
        "books": [6],
    },
    "Mrs. Croft": {
        "name": "Mrs. Croft",
        "other_names": ["Mrs. Croft", "Mrs Croft"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": ["Admiral Croft", "Mr. Croft"],
        "books": [6],
    },
    "Admiral Croft": {
        "name": "Admiral Croft",
        "other_names": ["Croft"],
        "category": ["Male", "Married", "Military"],
        "disqualifiers": ["Mrs. Croft"],
        "books": [6],
    },
    "Mrs Clay": {
        "name": "Mrs Clay",
        "other_names": ["Clay"],
        "category": ["Female", "Widowed", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
    "Mrs. Smith": {
        "name": "Mrs. Smith",
        "other_names": ["Smith"],
        "category": ["Female", "Married", "No profession"],
        "disqualifiers": [],
        "books": [6],
    },
}
