characters = {
    "Pierre Bezukhov": {
        "shortName": "Pierre",
        "other_names": ["Pierre", "Count Bezukhov", "Pyotr Kirillovich Bezukhov"],
        "category": ["Male", "Nobleman", "Philosopher", "Protagonist"],
        "disqualifiers": ["Kirill Bezukhov", "Elena Bezukhov"],
    },
    "Andrei Bolkonsky": {
        "shortName": "Andrei",
        "other_names": ["Andrei", "Prince Andrei", "Andrei Nikolaevich Bolkonsky"],
        "category": ["Male", "Nobleman", "Soldier", "Protagonist"],
        "disqualifiers": ["Nikolai Bolkonsky", "Maria Bolkonskaya"],
    },
    "Natasha Rostova": {
        "shortName": "Natasha",
        "other_names": ["Natasha", "Natalya Ilyinichna Rostova", "Countess Rostova"],
        "category": ["Female", "Noblewoman", "Protagonist"],
        "disqualifiers": ["Count Ilya Rostov", "Countess Rostova"],
    },
    "Nikolai Rostov": {
        "shortName": "Nikolai",
        "other_names": ["Rostov", "Count Nikolai Ilyich Rostov"],
        "category": ["Male", "Nobleman", "Soldier"],
        "disqualifiers": ["Count Ilya Rostov", "Countess Rostova"],
    },
    "Maria Bolkonskaya": {
        "shortName": "Maria",
        "other_names": ["Maria", "Princess Maria", "Marya Nikolaevna Bolkonskaya"],
        "category": ["Female", "Noblewoman", "Religious"],
        "disqualifiers": ["Nikolai Bolkonsky", "Andrei Bolkonsky"],
    },
    "Helene Kuragin": {
        "shortName": "Helene",
        "other_names": ["Helene", "Elena Vasilyevna Kuragina", "Countess Bezukhova"],
        "category": ["Female", "Noblewoman", "Antagonist"],
        "disqualifiers": ["Vasili Kuragin", "Anatole Kuragin"],
    },
    "Anatole Kuragin": {
        "shortName": "Anatole",
        "other_names": ["Anatole", "Anatole Vasilyevich Kuragin"],
        "category": ["Male", "Nobleman", "Antagonist"],
        "disqualifiers": ["Vasili Kuragin", "Helene Kuragin"],
    },
    "Prince Vassily Kuragin": {
        "shortName": "Vassily",
        "other_names": ["Vassily", "Vasili Kuragin", "Prince Vassily"],
        "category": ["Male", "Nobleman", "Politician"],
        "disqualifiers": ["Helene Kuragin", "Anatole Kuragin"],
    },
    "Sonia Rostova": {
        "shortName": "Sonia",
        "other_names": ["Sonia", "Sofya Alexandrovna"],
        "category": ["Female", "Noblewoman", "Orphan"],
        "disqualifiers": ["Count Ilya Rostov", "Countess Rostova"],
    },
    "Platon Karataev": {
        "shortName": "Platon",
        "other_names": ["Platon", "Karataev"],
        "category": ["Male", "Peasant", "Philosopher"],
        "disqualifiers": [],
    },
    "Count Ilya Rostov": {
        "shortName": "Ilya",
        "other_names": ["Ilya", "Count Rostov"],
        "category": ["Male", "Nobleman", "Family Head"],
        "disqualifiers": ["Nikolai Rostov", "Natasha Rostova"],
    },
    "Countess Natalya Rostova": {
        "shortName": "Natalya",
        "other_names": ["Countess Rostova"],
        "category": ["Female", "Noblewoman", "Family Head"],
        "disqualifiers": ["Nikolai Rostov", "Natasha Rostova"],
    },
    "Prince Nikolai Bolkonsky": {
        "shortName": "Nikolai",
        "other_names": ["Nikolai Andreyevich Bolkonsky"],
        "category": ["Male", "Nobleman", "Retired General"],
        "disqualifiers": ["Andrei Bolkonsky", "Maria Bolkonskaya"],
    },
    "Marya Dmitrievna Akhrosimova": {
        "shortName": "Marya",
        "other_names": ["Marya", "Akhrosimova"],
        "category": ["Female", "Noblewoman", "Family Friend"],
        "disqualifiers": [],
    },
    "Fyodor Dolokhov": {
        "shortName": "Dolokhov",
        "other_names": ["Fedya Dolokhov"],
        "category": ["Male", "Officer", "Antagonist"],
        "disqualifiers": [],
    },
    "Anna Pavlovna Scherer": {
        "shortName": "Anna Pavlovna",
        "other_names": ["Scherer"],
        "category": ["Female", "Noblewoman", "Courtier"],
        "disqualifiers": [],
    },
    "Prince Andrei Naryshkin": {
        "shortName": "Naryshkin",
        "other_names": ["Andrei Naryshkin"],
        "category": ["Male", "Nobleman", "Courtier"],
        "disqualifiers": [],
    },
    "Vasily Denisov": {
        "shortName": "Denisov",
        "other_names": ["Vasili Denisov"],
        "category": ["Male", "Soldier", "Nobleman"],
        "disqualifiers": [],
    },
}
