chapter_names = {
    "1": [
        "The Decanter of Tokay",
        "The Idea of North",
        "Lyra's Jordan",
        "The Alethiometer",
        "The Cocktail Party",
        "The Throwing Nets",
        "John Faa",
        "Frustration",
        "The Spies",
        "The Consul and the Bear",
        "Armour",
        "The Lost Boy",
        "Fencing ",
        "Bolvangar Lights ",
        "The Dæmon Cages ",
        "The Silver Guillotine",
        "The Witches",
        "Fog and Ice",
        "Captivity",
        "Mortal Combat",
        "Lord Asriel's Welcome",
        "Betrayal",
        "The Bridge to the Stars",
    ],
    "2": [
        "The Cat and the Hornbeam Trees",
        "Among the Witches",
        "A Children's World",
        "Trepanning",
        "Airmail Paper",
        "Lighted Fliers",
        "The Rolls-Royce",
        "The Tower of Angels",
        "Theft",
        "The Shaman",
        "The Belvedere",
        "Screen Language",
        "Æsahætter",
        "Alama Gulch",
        "Bloodmoss",
    ],
    "3": [
        "The Enchanted Sleeper",
        "Balthamos and Baruch",
        "Scavengers",
        "Ama and the Bats",
        "The Adamant Tower",
        "Preemptive Absolution",
        "Mary, Alone",
        "Vodka",
        "Upriver",
        "Wheels",
        "The Dragonflies",
        "The Break",
        "Tialys and Salmakia",
        "Know What It Is",
        "The Forge",
        "The Intention Craft",
        "Oil and Lacquer",
        "The Suburbs of the Dead",
        "Lyra and Her Death",
        "Climbing",
        "The Harpies",
        "The Whisperers",
        "No Way Out",
        "Mrs. Coulter in Geneva",
        "Saint-Jean-Les-Eaux",
        "The Abyss",
        "The Platform",
        "Midnight",
        "The Battle on the Plain",
        "The Clouded Mountain",
        "Authority's End",
        "Morning",
        "Marzipan",
        "There is Now",
        "Over the Hills and Far Away",
        "The Broken Arrow",
        "The Dunes",
        "The Botanic Garden",
    ],
}
